/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashRouteRouteImport } from './routes/_dash/route'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashTransactionsRouteImport } from './routes/_dash/transactions'
import { Route as DashProfileRouteImport } from './routes/_dash/profile'
import { Route as DashDashboardRouteImport } from './routes/_dash/dashboard'
import { Route as DashCategoriesRouteImport } from './routes/_dash/categories'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRouteRoute = DashRouteRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashTransactionsRoute = DashTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashProfileRoute = DashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRouteRoute,
} as any)
const DashCategoriesRoute = DashCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/categories': typeof DashCategoriesRoute
  '/dashboard': typeof DashDashboardRoute
  '/profile': typeof DashProfileRoute
  '/transactions': typeof DashTransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof DashRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/categories': typeof DashCategoriesRoute
  '/dashboard': typeof DashDashboardRoute
  '/profile': typeof DashProfileRoute
  '/transactions': typeof DashTransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dash': typeof DashRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_dash/categories': typeof DashCategoriesRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/profile': typeof DashProfileRoute
  '/_dash/transactions': typeof DashTransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/dashboard'
    | '/profile'
    | '/transactions'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/dashboard'
    | '/profile'
    | '/transactions'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/_dash'
    | '/auth'
    | '/_dash/categories'
    | '/_dash/dashboard'
    | '/_dash/profile'
    | '/_dash/transactions'
    | '/auth/login'
    | '/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashRouteRoute: typeof DashRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_dash/transactions': {
      id: '/_dash/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof DashTransactionsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/profile': {
      id: '/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashProfileRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/_dash/categories': {
      id: '/_dash/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof DashCategoriesRouteImport
      parentRoute: typeof DashRouteRoute
    }
  }
}

interface DashRouteRouteChildren {
  DashCategoriesRoute: typeof DashCategoriesRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashProfileRoute: typeof DashProfileRoute
  DashTransactionsRoute: typeof DashTransactionsRoute
}

const DashRouteRouteChildren: DashRouteRouteChildren = {
  DashCategoriesRoute: DashCategoriesRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashProfileRoute: DashProfileRoute,
  DashTransactionsRoute: DashTransactionsRoute,
}

const DashRouteRouteWithChildren = DashRouteRoute._addFileChildren(
  DashRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashRouteRoute: DashRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
